### ISSUE TITLE
fs.exists should not be used before readFile

### ISSUE THREAD

**Issue by mdvorak** [Avansai/properties-file#4]
https://github.com/Avansai/properties-file/blob/main/src/file/index.ts#L17

It is anti-pattern to call `existsSync` before `readFileSync`, since it introduces a race-condition - `readFileSync` still might fail, even with `ENOENT` error.
You should simply let it fail directly, and remove explicit check with custom Error.

See
https://nodejs.org/api/fs.html#fsexistspath-callback
> Using fs.exists() to check for the existence of a file before calling fs.open(), fs.readFile(), or fs.writeFile() is not recommended. Doing so introduces a race condition, since other processes may change the file's state between the two calls. Instead, user code should open/read/write the file directly and handle the error raised if the file does not exist.

**Comment by nbouvrette** [comment]
Thanks for reporting this @mdvorak - for some reason I was not getting any warning about this in VSCode (normally it tells you when something is deprecated). Also, I can't even find `existsSync` on the Node.js documentation.. which might explain why I was not getting it flagged.

In any case, this is now fixed by this [commit](https://github.com/Avansai/properties-file/commit/d99c07378fe7057473cb6e7b2615fe50935f330d) in version [2.1.32](https://github.com/Avansai/properties-file/releases/tag/2.1.32).

**Comment by mdvorak** [comment]
Well, `existsSync` is for some reason not deprecated (I'm pretty sure there was a lot of discussions about that), but it is still anti-pattern to use it before read, for the stated reasons.
